schema: "./path/to/schema/file.graphql"
generates:
  "./path/to/generated.ts":
    plugins:
    - add: "/* eslint-disable */"
    - typescript
    - typescript-operations
    - typescript-resolvers
    config:
      federation: true
      contextType: "../types#Context"
      useIndexSignature: true
      immutableTypes: true
      mappers:
